math_tasks/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import page_not_found

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^password/', page_not_found, {'exception': Exception('Not Found')}),
    url(r'^', include('registration.backends.hmac.urls')),
    url(r'^', include('news.urls', namespace='news')),
    url(r'^', include('tasks.urls', namespace='tasks')),
    url(r'^', include('django.contrib.flatpages.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^news/$', views.list, name='index'),
    url(r'^news/(?P<item_id>\d+)/$', views.item, name='item'),
]

tasks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.tournament, name='index'),
    url(r'^tasks/$', views.tasks, name='tasks'),
    url(r'^rating/$', views.rating, name='rating'),
    url(r'^answer/(?P<task_id>\d+)/$', views.answer, name='answer'),
]

news/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField(null=True)
    author = models.ForeignKey('auth.User')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField(default=False)

    def __str__(self):
        return self.title

tasks/models.py
from django.utils import timezone

from django.core.exceptions import ValidationError
from django.db import models

from .util import prepare_answer


class TimeMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Tournament(TimeMixin):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True)
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)
    is_current = models.BooleanField(default=False)

    class Meta:
        ordering = ('id',)
        index_together = (('start_time', 'end_time'),)

    def __str__(self):
        return self.title

    @classmethod
    def get_current(cls):
        return cls.objects.filter(is_current=True).get()


class Round(TimeMixin):
    title = models.CharField(max_length=200)
    start_time = models.DateTimeField(null=False)
    end_time = models.DateTimeField(null=False)
    is_last = models.BooleanField(default=False)
    tournament = models.ForeignKey(Tournament)

    class Meta:
        ordering = ('id',)
        index_together = (('start_time', 'end_time'),)

    def __str__(self):
        return '{}/{}'.format(self.tournament.title, self.title)

    def clean(self):
        if self.start_time >= self.end_time:
            raise ValidationError("Times are incorrect")

        # One round in moment
        round = Round.objects.exclude(id=self.id).filter(
                models.Q(start_time__range=(self.start_time, self.end_time)) |
                models.Q(end_time__range=(self.start_time, self.end_time))
            )
        if round.exists():
            raise ValidationError("One round in moment")

    @classmethod
    def get_current(cls):
        now = timezone.now()
        tournament = Tournament.get_current()
        for round in sorted(tournament.round_set.all(), key=lambda x: x.start_time):
            if round.start_time > now and round.end_time > now:
                return round
            if round.start_time <= now and round.end_time >= now:
                return round
            if round.is_last:
                return round


class Task(TimeMixin):
    creator = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    correct_answer = models.CharField(max_length=20)
    rounds = models.ManyToManyField(Round, related_name="tasks")

    class Meta:
        ordering = ('id',)
        index_together = (('id', 'correct_answer'),)

    def __str__(self):
        return self.title


class Answer(TimeMixin):
    author = models.ForeignKey('auth.User')
    value = models.CharField(max_length=20)
    task = models.ForeignKey(Task)
    is_success = models.NullBooleanField()

    class Meta:
        permissions = (
            ("can_create_answer", "Can create answer"),
        )

    def __str__(self):
        return self.value

    def save(self, *args, **kwargs):
        self.value = prepare_answer(self.value)
        self.is_success = Task.objects.filter(id=self.task.id).filter(correct_answer=self.value).exists()
        super(Answer, self).save(*args, **kwargs)


class Rating(models.Model):
    user = models.ForeignKey('auth.User')
    round = models.ForeignKey(Round)
    points = models.IntegerField()

    class Meta:
        ordering = ('points',)


from .signals import *

tasks/forms.py
from django import forms


class TaskForm(forms.Form):
    answer = forms.CharField(max_length=100, required=True)

news/views.py
from django.shortcuts import render
from django.http import Http404

from .models import Article


def list(request):
    try:
        news = Article.objects.filter(is_public=True).all()
    except Article.DoesNotExist:
        news = []

    return render(request, 'news/list.html', {
            'title': 'News',
            'menu': 'news',
            'news': news,
        }
    )


def item(request, item_id):
    try:
        item = Article.objects.filter(pk=item_id).filter(is_public=True).get()
    except Article.DoesNotExist:
        raise Http404

    return render(request, 'news/item.html', {
            'title': item.title,
            'menu': 'news',
            'item': item,
        }
    )

tasks/views.py
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_http_methods

from .models import Answer, Task, Rating
from .forms import TaskForm
from .tasks import calculate_rating_task


@login_required()
def tasks(request):
    now = timezone.now()
    params = {
        'title': 'Tasks',
        'menu': 'tasks',
        'can_answer': can_answer(request),
        'tasks': Task.objects.filter(rounds=request.round) if request.round.start_time <= now else []
    }

    if params['tasks'] and params['can_answer']:
        answers = {}
        for answer in Answer.objects.filter(author=request.user.id).filter(task__in=params['tasks']).order_by('id'):
            if answers.get(answer.task_id):
                answers[answer.task_id].append(answer)
            else:
                answers[answer.task_id] = [answer]
        params['answers'] = answers

    return render(request, 'tasks/tasks.html', params)


def rating(request):
    rating = Rating.objects.filter(round=request.round)

    return render(request, 'tasks/rating.html', {
            'title': 'Rating',
            'menu': 'rating',
            'rating': rating,
        }
    )


def tournament(request):
    rounds = request.tournament.round_set.all()

    return render(request, 'tasks/tournament.html', {
            'title': request.tournament.title,
            'menu': 'tournament',
            'rounds': rounds,
        }
    )


def can_answer(request):
    return not request.user.is_staff and \
           (not request.round.is_last or request.round.is_last and request.user.has_perm('tasks.can_create_answer'))


@require_http_methods(["POST"])
@login_required()
def answer(request, task_id):
    form = TaskForm(request.POST)
    if not form.is_valid():
        return HttpResponse("Error")

    task = get_object_or_404(Task, pk=task_id)
    Answer(
        author=User.objects.filter(pk=request.user.id).get(),
        task=task,
        value=form.data.get('answer')
    ).save()
    calculate_rating_task.delay(round_id=request.round.id)
    return redirect('/tasks/')

tasks/templates/tasks/rating.html
{% extends 'base_layout.html' %}
{% load staticfiles %}

{% block content %}
    <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Username</th>
            <th>Points</th>
          </tr>
        </thead>
        <tbody>
          {% for row in rating %}
              <tr>
                <td>{{ loop.index }}</td>
                <td>{{ row.user.username }}</td>
                <td>{{ row.points }}</td>
              </tr>
          {% endfor %}
        </tbody>
    </table>
{% endblock %}

tasks/templates/tasks/tasks.html
{% extends 'base_layout.html' %}
{% load staticfiles %}

{% block content %}
  {% for task in tasks %}
    <h3>{{ task.title }}</h3>
    <p>{{ task.text|safe|escape }}</p>
    <form action="/answer/{{ task.id }}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Check">
    </form>
    <hr>
  {% endfor %}
{% endblock %}

templates/base_layout.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% if flatpage.title %}{{ flatpage.title }}{% else %}{{ title }}{% endif %}</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://getbootstrap.com/docs/3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/3.3/assets/css/ie10-viewport-bug-workaround.css">
    <link rel="stylesheet" href="{% static "custom/css/custom.css" %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="https://getbootstrap.com/docs/3.3/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

</head>

<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">{{ request.tournament.title }}</a></li>
            <li class="{% if menu == "news" %}active{% endif %}"><a href="/news/">{% trans "News" %}</a></li>
            <li><a href="/faq/">{% trans "FAQ" %}</a></li>
            <li><a href="/rating/">{% trans "Rating" %}</a></li>
              {% if user.is_authenticated %}
                <li><a href="/tasks/">{% trans "Tasks" %}</a></li>
                <li><a href="/logout/">{% trans "Logout" %}</a></li>
            {% else %}
                <li><a href="/login/">{% trans "Login" %}</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <h1>{% if flatpage.title %}{{ flatpage.title }}{% else %}{{ title }}{% endif %}</h1>
        {% block content %}
        {% endblock %}
    </div> <!-- /container -->



    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <p class="copyright text-muted">Copyright &copy; Zarina Sayfullina 2017</p>
            </div>
        </div>
    </footer>


    <!-- Bootstrap Core JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie-emulation-modes-warning.js"></script>
    <script src="https://getbootstrap.com/docs/3.3/dist/js/bootstrap.min.js"></script>
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src='{% static "custom/js/custom.js" %}'></script>

</body>

</html>

templates/news/item.html
{% extends 'base_layout.html' %}
{% load staticfiles %}

{% block content %}
    {{ item.text|safe|escape }}
{% endblock %}

templates/news/list.html
{% extends 'base_layout.html' %}
{% load staticfiles %}

{% block content %}
<ul>
  {% for item in news %}
    <li><a href="/news/{{ item.id }}/">{{ item.title }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

templates/static.html
{% extends 'base_layout.html' %}
{% load staticfiles %}

{% block content %}
{{ flatpage.content }}
{% endblock %}

templates/tasks/rating.html
{% extends 'base_layout.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
    <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>{% trans "Username" %}</th>
            <th>{% trans "Points" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for row in rating %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ row.user.username }}</td>
                <td>{{ row.points }}</td>
              </tr>
          {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/tasks/tasks.html
{% extends 'base_layout.html' %}
{% load staticfiles %}
{% load i18n %}
{% load tasks_filters %}

{% block content %}
  {% for task in tasks %}
    <h3>{{ task.title }}</h3>
    {{ task.text|safe|escape }}
    {% if can_answer %}
        <form action="/answer/{{ task.id }}/" method="post">
            {% csrf_token %}
            <div class="input-group">
                <input type="text" name="answer" required="" maxlength="100" id="id_answer" class="form-control"
                       placeholder="{% trans "Answer" %}">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        {% trans "Check" %}
                    </button>
                </div>
            </div>
        </form>
        {% with answers|get_item:task.id as answer_task %}
        {% if answer_task %}
            <table class="table table-hover answers">
                <tbody>
                    {% for answer in answer_task  %}
                        <tr>
                            <td>{{ answer.value }}</td>
                            <td>{{ answer.created_at|date:"Y-m-d H:i" }}</td>
                            <td><i class="glyphicon glyphicon-{% if answer.is_success %}ok{% else %}remove{% endif %}"></i></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
        {% endwith %}
    {% endif %}
    <hr>
  {% endfor %}
{% endblock %}

templates/tasks/tournament.html
{% extends 'base_layout.html' %}
{% load staticfiles %}

{% block content %}

    {{ request.tournament.description|safe|escape}}

    <hr>
    <ul>
    {% for round in rounds %}
        <li>{{round.start_time|date:"Y-m-d H:i"}} - {{round.end_time|date:"Y-m-d H:i"}} // {{round.title}}</li>
    {% endfor %}
    </ul>
{% endblock %}